USE ROLE ACCOUNTADMIN;

-- Create the `transform` role and assign it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Create a default warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

CREATE USER IF NOT EXISTS dbt
  PASSWORD=''
  LOGIN_NAME=''
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_NAMESPACE='ECOMMERCE.RAW_DATA'
  COMMENT='DBT user used for data transformation';
ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt;

CREATE DATABASE IF NOT EXISTS ECOMMERCE;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE.ANALYTICS;

USE DATABASE ECOMMERCE;
USE SCHEMA RAW_DATA;

GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE ECOMMERCE TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE ECOMMERCE TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ECOMMERCE TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA ECOMMERCE.RAW_DATA TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA ECOMMERCE.RAW_DATA TO ROLE TRANSFORM;

CREATE STAGE IF NOT EXISTS my_csv_stage;

LIST @my_csv_stage;

CREATE FILE FORMAT IF NOT EXISTS csv_file_format
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE;

CREATE TABLE IF NOT EXISTS orders (
    order_id VARCHAR(100),
    customer_id VARCHAR(100),
    order_date DATE
);

CREATE TABLE IF NOT EXISTS customers (
    customer_id VARCHAR(100),
    name VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS shipments (
    shipment_id VARCHAR(100),
    order_id VARCHAR(100),
    status VARCHAR(50),
    shipped_at TIMESTAMP_NTZ,
    delivered_at TIMESTAMP_NTZ
);

COPY INTO orders
FROM @my_csv_stage/orders.csv
FILE_FORMAT = (FORMAT_NAME = csv_file_format)
ON_ERROR = 'CONTINUE';

COPY INTO customers
FROM @my_csv_stage/customers.csv
FILE_FORMAT = (FORMAT_NAME = csv_file_format)
ON_ERROR = 'CONTINUE';

COPY INTO shipments
FROM @my_csv_stage/shipments.csv
FILE_FORMAT = (FORMAT_NAME = csv_file_format)
ON_ERROR = 'CONTINUE';